- name: Bootstrap
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - rmb938.bootstrap

- name: Step CA
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - step-ca
  vars:
    ras:
      acme:
        port: 8443
        policy:
          x509:
            allow:
              dns:
                - "*.rmb938.me"
                - "*.us-homelab1.hl.rmb938.me"
                - "*.tailnet-047c.ts.net"
        provisioner:
          type: ACME
          name: acme
          forceCN: true
          challenges:
            - http-01
      haproxy:
        port: 9443
        policy:
          x509:
            allow:
              dns:
                - "*.haproxy.us-homelab1.hl.rmb938.me"
            allowWildcardNames: true
        provisioner:
          type: x5c
          name: x5c
          roots: >-
            LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0akNDQVdpZ0F3SUJBZ0lVTDF6UDBibHdrWHdEZG9YVjJnaytMSmg1amxBd0NnWUlLb1pJemowRUF3TXcKSURFZU1Cd0dBMVVFQXhNVlUzUmxjQ0JZTlVNZ1NFRlFjbTk0ZVNCU2IyOTBNQjRYRFRJMU1ESXhOekUwTlRjMApOMW9YRFRRMU1ESXhOekV4TWpJeE4xb3dJREVlTUJ3R0ExVUVBeE1WVTNSbGNDQllOVU1nU0VGUWNtOTRlU0JTCmIyOTBNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRWZ1cStUeEdRLzhZbmVaVkswbWd3M3psdHh6ZVEKYVhuVkVLQTlhRm91bUZBU3ErS0UycnArT2RVRmZNUUxWbDJ6d2I3K01ZWGs3RVpqcmpudmtGN3BjMnU2UFV3Sgo5c3VMczFML0J4ZG1kVHV6TkR3bnVMZEFtb24zbzVzVmpmSG5vMk13WVRBT0JnTlZIUThCQWY4RUJBTUNBUVl3CkR3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNyQVhUWHlEOWk0L0hwM2ZFRWszcmZFK0Q1Y3cKSHdZRFZSMGpCQmd3Rm9BVUNyQVhUWHlEOWk0L0hwM2ZFRWszcmZFK0Q1Y3dDZ1lJS29aSXpqMEVBd01EYUFBdwpaUUl4QU9uRlVYWmJkKzhWSG02SSsxTGYycjFuMHYvSHVPTjhPYUk5QjlBU2tEYVRzWVptY3k3U21kb0hSejdSCm9ERkIxZ0l3RUJURkNqQnlEYVlzN2xBRmZCZkNYR0QvNm96a2J1NmZYQlBnenpnYkloaGRJY2dPZ1FwejNNUE8KSFYybnA5VG4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
