# - name: Bootstrap
#   hosts: all
#   become: true
#   remote_user: ubuntu
#   roles:
#     - rmb938.bootstrap

- name: Step CA
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - step-ca
  vars:
    ras:
      - name: acme
        port: 8443
        policy:
          x509:
            allow:
              - "*.rmb938.me"
              - "*.us-homelab1.hl.rmb938.me"
              - "*.tailnet-047c.ts.net"
        provisioners:
          - type: ACME
            name: acme
            forceCN: true
            challenges:
              - http-01
            options:
              x509:
                template: |
                  {
                    "subject": {
                      "commonName": {{ toJson .Subject.CommonName }},
                      "country": "US",
                      "organization": "Home Lab",
                      "organizationalUnit": "ACME",
                      "province": "Minnesota"
                    },
                    "sans": {{ toJson .SANs }},
                  {{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }}
                    "keyUsage": ["keyEncipherment", "digitalSignature"],
                  {{- else }}
                    "keyUsage": ["digitalSignature"],
                  {{- end }}
                    "extKeyUsage": ["serverAuth", "clientAuth"]
                  }
      # - name: haproxy
      #   port: 9443
      #   policy:
      #     x509:
      #       allow:
      #         - "*.haproxy.us-homelab1.hl.rmb938.me"
      #   provisioners:
      #     - type: x5c
      #       name: x5c
      #       roots:
      #         - "a base64 encoded list of root certificate PEM blocks used for validating X5C tokens"
      #       options:
      #         x509:
      #           template: |
      #             {
      #               "subject": {
      #                 "commonName": {{ toJson .Subject.CommonName }},
      #                 "country": "US",
      #                 "organization": "Home Lab",
      #                 "organizationalUnit": "HAProxy",
      #                 "province": "Minnesota"
      #               },
      #               "sans": {{ toJson .SANs }},
      #             {{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }}
      #               "keyUsage": ["keyEncipherment", "digitalSignature"],
      #             {{- else }}
      #               "keyUsage": ["digitalSignature"],
      #             {{- end }}
      #               "extKeyUsage": ["serverAuth", "clientAuth"]
      #             }
